name: 'Generate pip freeze file.'

inputs:
  python_version:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        python_bin="python3"
        [[ "$INPUT_python_version" == "2.7" ]] && python_bin="python"

        ./venv/bin/${python_bin} -m pip freeze > requirements.txt
      shell: bash
