---
name: 'Lint it!'
description: 'Lint this repo.'

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-venv
        pushd $HOME
          python3 -m venv --clear .venv_linter
        popd
        $HOME/.venv_linter/bin/python3 -m pip install -U setuptools pip
        $HOME/.venv_linter/bin/python3 -m pip install -e .[dev]
      shell: bash

    - name: Test with pytest
      run: |
        $HOME/.venv_linter/bin/python3 -m py.test -m "linter" --lint-code
      shell: bash
...
