---
name: 'Lint it!'
description: 'Lint this repo.'

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        python3 -m pip install --user -U setuptools pip
        python3 -m pip install --user -e .[dev]
      shell: bash

    - name: Test with pytest
      run: |
        python3 -m py.test -m "linter" --lint-code
      shell: bash
...
