---
name: 'Test it!'
description: 'Test this repo.'

inputs:
  python_version:
    required: true

runs:
  using: "composite"
  steps:
    - run: |-
        sudo apt update
        if [[ "$INPUT_python_version" == "2.7" ]] ; then
          _python_bin=~/.venv/bin/python
          sudo apt install -y virtualenv python-pip
          virtualenv -p python2.7 \
            --clear --no-setuptools --no-pip --no-wheel ~/.venv
        else
          _python_bin=~/.venv/bin/python3
          sudo apt install -y python3-venv
          python3 -m venv --clear ~/.venv
        fi

        "$_python_bin" -m pip install -U setuptools pip
        "$_python_bin" -m pip install -e .[dev]
        "$_python_bin" -m py.test -m "not linter" \
            --cov=./ --cov-report="xml:_reports/coverage-${INPUT_python_version}.xml"
      shell: bash
...
