name: 'Test it!'
description: 'Test this repo.'

inputs:
  python_version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install virtualenv (Python 2.7).
      run: |
        if [[ "$INPUT_python_version" == "2.7" ]] ; then
          sudo apt update
          sudo apt install -y virtualenv python-pip
        fi
      shell: bash

    - name: Create venv.
      run: |
        if [[ "$INPUT_python_version" == "2.7" ]] ; then
          virtualenv -p python2.7 --clear venv
        else
          python3 -m venv --clear venv
        fi
      shell: bash

    - name: Install dependencies
      run: |
        python_bin="python3"
        [[ "$INPUT_python_version" == "2.7" ]] && python_bin="python"

        ./venv/bin/${python_bin} -m pip install -U setuptools pip
        ./venv/bin/${python_bin} -m pip install -e .[dev]
      shell: bash

    - name: Test with pytest
      run: |
        python_bin="python3"
        [[ "$INPUT_python_version" == "2.7" ]] && python_bin="python"

        ./venv/bin/${python_bin} -m py.test -m "not linter"
      shell: bash
