---
name: codecov

on:
  workflow_run:
    workflows:
      - test
    types:
      - completed

jobs:
  on_success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: test-result
      - name: "foo 0"
        run: ls -lhta
        shell: "bash"
      - name: "foo 1"
        run: ls -lhta _reports/
        shell: "bash"
...
